name: Sudoku Move Handler

on:
  issues:
    types: [opened, edited]

jobs:
  process_move:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # It's good to specify a specific version to avoid surprises.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests  # Install necessary Python packages.

    - name: Validate and update the Sudoku board
      run: python .github/scripts/validate_and_update.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update Sudoku board from GitHub Issue"
        git push
